### ISSUE TITLE
why I not play in "https://www.slumbot.com/#", but the stats datas changes automatically

### ISSUE THREAD

**Issue by zqbAse** [ericgjackson/slumbot2017#11]
Why I not play in "https://www.slumbot.com/#", but the stats datas changes automatically.
The picture is the data before, but now it's different.
![edd](https://user-images.githubusercontent.com/28745244/147525361-0daf7d45-3e42-4b94-855d-4660ad95ea8e.png)

**Comment by ericgjackson** [comment]
Looking into this.

**Comment by ericgjackson** [comment]
Think I figured out what is happening.

To explain what's going on, I need to provide a little background.  There's a possible way to cheat that the website needs to protect against.  Suppose someone gets into a bad situation in a hand.  For example, he raises to 10,000 chips on a bluff, and Slumbot re-raises to 20,000.  The user can choose never to respond.  There has to be a timeout so that at some point the user loses the 10,000 chips he has put into the pot.  Otherwise the user can cheat.

To prevent this, we periodically go through all the in-progress hands on the server and see which ones have had no action in the last 24 hours.  The user forfeits those hands and Slumbot receives all the chips in the pot.  Your account had a couple hundred of those hands and they were forfeited.

**Comment by zqbAse** [comment]
Thanks

**Comment by brewer-b** [comment]
Sorry for the unrelated post on a closed issue, but doesn't it seem weird for this agent to have a raw winrate of 10bb/100 and a baseline winrate of 140bb/100? Is it possibly related to this issue? Or do you have an ideas what may be causing it?

**Comment by ericgjackson** [comment]
Yes, I think it may be related to this issue.  I believe zqbAse identified this exploit where his agent could "walk away from the table" (i.e., abandon the hand) whenever it gets into a bad spot.

The site is supposed to prevent this, but due to a bug this wasn't being caught earlier.  (That bug is now fixed.)

**Comment by yegorrr** [comment]
in their research (https://arxiv.org/pdf/2201.11580.pdf) they stated that they beat slumbot for over 700mbb/h but the leaderboard says aqbAgent is winning "only" 10.77bb/100. but its baseline winnings are 140.6bb/100 which is rougly twice as much

and i've seen a few other mentions of beating slumbot for 20+bb/100 but currently noone has this winrate in the leaderboard, do people get removed from it?

**Comment by ThomasTel** [comment]
Yeah it seems we get removed after our winrate decreased.
